### ISSUE TITLE
License

### ISSUE THREAD

**Issue by excelisor1** [dnlnln/generate-sql-merge#43]
I am looking to use this however I am unable to find information on the license.
Is it possible to add a license?

**Comment by dnlnln** [comment]
This procedure was adapted from [sp_generate_inserts](http://vyaskn.tripod.com/code.htm#inserts), written by Narayana Vyas Kondreddi. I made a number of attempts to get in touch with Vyas in order to determine how his work may be used, however I received no reply. Therefore, at this stage, I am unfortunately unable to assign a license to this project.

**Comment by flipdoubt** [comment]
@readyroll , did you try contacting his hotmail address from the [wayback machine](https://web.archive.org/web/20040405133814/https://vyaskn.tripod.com/contact.htm)?

**Comment by dnlnln** [comment]
@flipdoubt I did about 9 years ago, but I've just tried him again. Fingers crossed we hear back :)

**Comment by dnlnln** [comment]
I didn't hear back from Vyas, but I mentioned in my email from 2021 that I planned to publish this project with an MIT License and haven't heard back in the 2 years since. Now that I've added the license, I've just dropped him another email and also contacted him on LinkedIn. I've asked if he has any concerns about it to get in touch.
