### ISSUE TITLE
Large number of columns causes @Column_List_For_Check to be truncated

### ISSUE THREAD

**Issue by awingrove** [dnlnln/generate-sql-merge#55]
Hi,

Thanks for the great proc! I'm using it on a table with a large number of columns (76). I noticed though that the @Column_List_For_Check gets truncated in this case. I just change the declare to varchar(max) instead of varchar(8000) and it all looks good to me.

Thanks again!

**Comment by dnlnln** [comment]
I think that this issue is owing to this proc originally having been designed for SQL Server 2000 (back when it was `sp_generate_inserts`), which didn't support the max precision. I'll get this sorted out very shortly, and also check the other variable precisions while I'm at it. Thanks for the report!

**Comment by awingrove** [comment]
Great, thanks! 😃

**Comment by dnlnln** [comment]
@awingrove PR #57 has now been raised. If you have a moment, would you mind confirming that the `fix-column-list-truncation` branch resolves the issue? Thanks!
