### ISSUE TITLE
Creation error in Azure Sql server database

### ISSUE THREAD

**Issue by CTBT** [dnlnln/generate-sql-merge#68]
It looks like  the sp_generate_merge procedure can not be created inside an azure sql server database.

`Checking for the existence of this procedure
Procedure already exists. So, dropping it
Created the procedure
Meldung 2812, Ebene 16, Status 62, Zeile 901
Could not find stored procedure 'sp_MS_marksystemobject'.
Granting EXECUTE permission on sp_generate_merge to all users
Done
`

So the procedure depends on database objects that are only available with on-premise sql-server.

Is there a solution for that ?

Version: 12.0.2000.8

**Comment by dnlnln** [comment]
That error occurs because usually the procedure is created inside the `master` database (rather than a user database) and marked as a system object, in order for it to be callable in any DB as if it were a local object. With Azure, such system objects are not supported.

Having said that, the procedure should still happily install into the user database and be usable, in spite of the errors you are receiving. If it does indeed work on Azure, I'll look at whether these errors can be suppressed to avoid the misleading messages.

**Comment by dnlnln** [comment]
Fixed by 2dc9e30340737e49596408bdf524bab6746c98c1

When you install the proc on Azure SQL, it will now be created within the current database, rather than `master`. The errors have also been addressed. See the README.md file under "Installation" for more info.
